version: 2

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: node:8
    # environment:
      # - TERM: XTERM
    steps:
      - checkout
      - run: npm install
      - run: npm test
