version: 2

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: node:8
    environment:
      - COLUMNS: 100
      - LINES: 24
      - TERM: XTERM
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: stty size
      - run: node size.js
